# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
 
      - name: Set google credentials
        id: add-google-credentials
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "settings.json"
          json: '{ "integration-url": "https://kosy-software.github.io/google-drive-table-app/" }' # TODO.... alter the app so you can set it up for multiple apps
          
      - name: TSC actions
        uses: stepek/tsc-action@1.0.0
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
